# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doviz_arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(800, 500)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.central_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 781, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.v_box = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.v_box.setContentsMargins(0, 0, 0, 0)
        self.v_box.setObjectName("v_box")
        self.h_box_title = QtWidgets.QHBoxLayout()
        self.h_box_title.setObjectName("h_box_title")
        self.label_currency = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_currency.setFont(font)
        self.label_currency.setObjectName("label_currency")
        self.h_box_title.addWidget(self.label_currency, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignBottom)
        self.label_gold = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_gold.setFont(font)
        self.label_gold.setObjectName("label_gold")
        self.h_box_title.addWidget(self.label_gold, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignBottom)
        self.label_index = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_index.setFont(font)
        self.label_index.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_index.setObjectName("label_index")
        self.h_box_title.addWidget(self.label_index, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignBottom)
        self.v_box.addLayout(self.h_box_title)
        self.h_box_info = QtWidgets.QHBoxLayout()
        self.h_box_info.setObjectName("h_box_info")
        self.text_currency = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.text_currency.setFont(font)
        self.text_currency.setObjectName("text_currency")
        self.h_box_info.addWidget(self.text_currency)
        self.text_gold = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.text_gold.setFont(font)
        self.text_gold.setObjectName("text_gold")
        self.h_box_info.addWidget(self.text_gold)
        self.text_index = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.text_index.setFont(font)
        self.text_index.setObjectName("text_index")
        self.h_box_info.addWidget(self.text_index)
        self.v_box.addLayout(self.h_box_info)
        self.h_box_button = QtWidgets.QHBoxLayout()
        self.h_box_button.setObjectName("h_box_button")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h_box_button.addItem(spacerItem)
        self.button_update = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_update.setFont(font)
        self.button_update.setObjectName("button_update")
        self.h_box_button.addWidget(self.button_update)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h_box_button.addItem(spacerItem1)
        self.v_box.addLayout(self.h_box_button)
        main_window.setCentralWidget(self.central_widget)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Currency, Gold, Index"))
        self.label_currency.setText(_translate("main_window", "Currency"))
        self.label_gold.setText(_translate("main_window", "Gold"))
        self.label_index.setText(_translate("main_window", "Index"))
        self.button_update.setText(_translate("main_window", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())

